### ISSUE TITLE
Execute Graph Model (EGM)

### ISSUE THREAD

**Issue by myunusov** [myunusov/pm#28]
Subtasks
- [x] #8  Add editor and calculator for Execute Graph Model
- [x] #29 sum of the probabilities of all possible cases of one switch must be 1 or less
- [x] #30 The bottleneck node must be colored
- [x] #31 The routine can be reordered
- [ ] #32 Calculate speed-Up for EGM
- [x] #83 Visualization D&D operation on tree
